execute_process(COMMAND "${PROGRAM}" RESULT_VARIABLE result OUTPUT_VARIABLE actual ERROR_VARIABLE errors TIMEOUT 10)
if(NOT result STREQUAL "0")
  message(FATAL_ERROR "Example failed (${result}): ${errors}")
endif()
if(NOT errors STREQUAL "")
  message(FATAL_ERROR "Unexpected stderr: ${errors}")
endif()
file(READ "${EXPECTED}" expected)
string(REPLACE "\r\n" "\n" actual "${actual}")
string(REPLACE "\r\n" "\n" expected "${expected}")
if(NOT actual STREQUAL expected)
  message(FATAL_ERROR "Output mismatch. Expected [${expected}], got [${actual}]")
endif()
