execute_process(COMMAND "${PROGRAM}" RESULT_VARIABLE result OUTPUT_VARIABLE actual ERROR_VARIABLE errors)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Example failed (${result}): ${errors}")
endif()
file(READ "${EXPECTED}" expected)
string(REPLACE "\r\n" "\n" actual "${actual}")
string(REPLACE "\r\n" "\n" expected "${expected}")
if(NOT actual STREQUAL expected)
  message(FATAL_ERROR "Output mismatch. Expected [${expected}], got [${actual}]")
endif()
